version: '3.8'

services:
  web:
    build: .
    container_name: fastapi_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOSTNAME: 192.168.1.214
      DATABASE_PORT: 5432
      DATABASE_NAME: edgedevmaster
      DATABASE_USERNAME: edgedevmaster
      DATABASE_PASSWORD: edgedevmaster
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: edgedevmaster
      POSTGRES_USER: edgedevmaster
      POSTGRES_PASSWORD: edgedevmaster
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
